### ISSUE TITLE
anime: シン・アニメ当てクイズの仕様を決める

### ISSUE THREAD

**Issue by hideo54** [tsg-ut/slackbot#154]
現在のアニメ当てクイズ(beta; `anime/` on `anime` branch)は、博多市のPCからの実行を前提とした仕様であり、博多市のローカル環境からアクセスできるアニメを素材としています。
しかし素材不足の状況にあることから、hideo54の持つアニメ録画をも素材として提供できる仕様にしたいです。
「ひでおアニメ当てクイズ」として別途botを作るという案も上がりましたが、使い勝手を考えれば、やはり1つのbotに集約するべきだと思います。

各素材提供者が決められた仕様で素材を返すWebサーバーを立て、アニメ当てクイズがそれにアクセスする、という形にできればなと思います。

**Comment by hideo54** [comment]
## 素材鯖選定法

* 楽なやつ: あらかじめ手動で各素材鯖と乱数閾値を設定しておく(例: 70%の確率でhideo54素材鯖にアクセス)。そんな急激に各自の素材数が変わることはないやろ。鯖が止まってたらどんまい。
* 真面目なやつ: 各素材鯖が稼働開始時や素材追加時に `{ isAvailable: true, number_of_titles: 120 }` みたいなstatusをbot鯖に送る。bot鯖は最新のstatusとその素材数を元に素材鯖を選ぶ。

## 素材レスポンス

```
{ title: "少女終末旅行", // 答えになる
  detail: "第5話「昼寝」", // クイズ終了時に出すプチ情報。問題にはしない
  thumbnails: [ "https://...", ... ] // 問題になる
}
```
何をどんな確率で出すかは各素材提供者におまかせ。

---

みたいな感じでどうでしょう。 @hakatashi とか

**Comment by cookie-s** [comment]
素材レスポンス、thumbnailsにあるURLは、半永久的にアクセスできることが保証されるんでしょうか。また、それはpublic？

**Comment by hakatashi** [comment]
「楽なやつ」プランで良いと思う。加えて鯖が止まってたら他の鯖にフォールバックする仕様を実装すると良さそう。

素材レスポンスもそれでいいと思うけど、くっきーの言ったとおりthumbnailsのavailabilityはちゃんと協議したほうが良いと思う。ちなみに博多市の実装したやつはcloudinaryに上げてるので半永久的にアクセス可能。

**Comment by hideo54** [comment]
了解 > 楽なやつ

> availability
それねーーー書き忘れたけど僕もどうしようか迷ってるんですよ。まあ各素材提供者におまかせ、でいいと思うんだけど、それはそうとして。
僕らが楽しむことだけを考えると半永久的にpublic(ただしURLは十分複雑)に越したことはないし、別に気にする容量でもない。それに後からslacklogで読み返せる。
しかし、その他の事情を考えると、どうしたものかなあ。

**Comment by cookie-s** [comment]
- 1hourまたは1回アクセスでリンクを切らしてよい
- 24hourはアクセス可能であること
- まあずっと保持してほしいな

などがあるとおもっています

**Comment by hideo54** [comment]
これもうやる気ないです
