### ISSUE TITLE
Events APIの開発を楽にする

### ISSUE THREAD

**Issue by pizzacat83** [tsg-ut/slackbot#176]
Eventが特定のURL1つ（今は https://slackbot.tsg.ne.jp/slack-event ）にHTTPリクエストを投げる形式になっており，RTM APIやWeb APIのように試しに動かしてみようができない

博多市「subscribe形式のプロキシを実装するとか? 激しんどそう」

**Comment by cookie-s** [comment]
これ、たぶんSlackのSocket Modeが解決することなんですよね。
なので、人々のローカル開発のときはSocket Modeで開発するオプションを案内する（READMEないしscrapboxで）という方法があると思います。

Relates #424

**Comment by cookie-s** [comment]
npm run devのときだけsocket-modeにする、とかすると、RTMと気持ち変わらず、websocket通信になるので、ngrokとかもいらない、と思う。　なおsocket-modeでの接続まだしたことないです

**Comment by cookie-s** [comment]
Socket Modeはappに対してall or nothingで、入れるとHTTPのEvents APIが飛んでこない仕様だった気がするのでなしです

なにかを作ったので、Scrapboxを「Events API」で検索して見つけてね
