### ISSUE TITLE
botのエラーを外部に流して見やすくする

### ISSUE THREAD

**Issue by pizzacat83** [tsg-ut/slackbot#182]
> 実は[ここらへん](https://github.com/tsg-ut/slackbot/blob/master/index.js#L4)を変えるだけでいい感じになるかもしれない。ただ無限ループとかになったときにしんどいのでうまいことthrottleする仕組みはほしい気がする

**Comment by cookie-s** [comment]
azaikaくんがpapertrailに流してくれました https://github.com/tsg-ut/slackbot/pull/360
ログイン情報はscrapboxを「papertrail」とかで検索してください
