### ISSUE TITLE
slack-log: botから呼べる関数を用意する

### ISSUE THREAD

**Issue by pizzacat83** [tsg-ut/slackbot#187]
非userのbotがリンクを貼ってもlink_sharedが発火せず展開してもらえないが、unfurlの引数に渡すattachmentを生成する関数をbotが呼べるようになったら、slack-logのリンクを共有したいbotはその関数を読んで自分でattachmentに付け足して投稿できる！

**Comment by cookie-s** [comment]
`slack-log` (slackbot名)には、slack-log (ツール名)のURLがSlackに投稿されると、その投稿内容をSlackのattachmentとして展開してくれる機能がある（ogpが入っているウェブページのリンクを貼ったときと同じような挙動）。
https://github.com/tsg-ut/slackbot/blob/45da6108085fe5eaf136df9edbbb1b2bad0763dd/slack-log/index.ts#L63-L64

上記機能の実装は、tsgbotの設定画面(cf. Event Subscriptions / App unfurl domains)でslacklogのドメイン名を登録しておくとbotにlink_sharedイベントが飛んでくるから、それに対していい感じにAPIを呼んでやる、というふうになっている。ところが、Slackの仕様として、非user (i.e. bot, e.g. tsg-ut/slackbot自身)が投稿したときは、link_shared eventが飛んでこないっぽく、よって非userがslacklogのURLを投稿したときは展開されない。

これにたいして、slack-log内に、他のbotから呼んで補間できる関数を作ろう、という話

**Comment by cookie-s** [comment]
https://github.com/tsg-ut/slackbot/issues/188#issuecomment-1233643745
