### ISSUE TITLE
slack-log: unfurlの名前欄をSlackの形式に合わせる

### ISSUE THREAD

**Issue by pizzacat83** [tsg-ut/slackbot#189]
attachment一番上の名前欄について。
多分今usernameになっているが，lib/slackUtilsのgetMemberNameだっけ？使うとSlackと同じくdisplay_nameを出せるはず

**Comment by cookie-s** [comment]
まあとりあえず閉じてええやろ！ getMemberNameしたくなったら新たにIssueたててくれ
