### ISSUE TITLE
アニソン当てクイズhardで、正答した後もbotがヒントを出し、続く

### ISSUE THREAD

**Issue by Szkieletor37** [tsg-ut/slackbot#286]
https://slack-log.tsg.ne.jp/C7AAX50QY/1589885526.127000

**Comment by Szkieletor37** [comment]
https://github.com/tsg-ut/slackbot/blob/e333ae5c8ec02bd2ceb33ea2ee297f9587a41478/anime/anison.js#L310

anime-song-hard-answerがachievementに存在しないので、ここで `state.answer` がnullにならずに `onTick()` 内の処理が続く

**Comment by hakatashi** [comment]
デバッグの天才? ついでに修正してよさそう

**Comment by Szkieletor37** [comment]
実績の方を追加するという意味ですか
