### ISSUE TITLE
oogiri: BET可能枚数のところに最大意味登録可能数が表示されてしまう

### ISSUE THREAD

**Issue by settyan117** [tsg-ut/slackbot#293]
index.tsの309行目が、305行目とおなじ`game.maxMeanings`を表示していてよくなさそう。コード全体をまだ読めていないんですが、たぶんBET可能枚数は`game.maxCoins`っぽい？

https://github.com/tsg-ut/slackbot/blob/ec5e6a58a520412bdcc12add077fbb8113c8ceb3/oogiri/index.ts#L302-L311

**Comment by hakatashi** [comment]
百億理ある
