### ISSUE TITLE
sorting-riddles: 実績を募集しています

### ISSUE THREAD

**Issue by n4o847** [tsg-ut/slackbot#339]
誰か実績を考えてくれませんか？

ところでソートなぞなぞは sort-nazonazo から sorting-riddles に名前が変わっていて sorting-riddles というブランチにあります。

**Comment by Szkieletor37** [comment]
どういう条件での実績を考えていますか

**Comment by Szkieletor37** [comment]
実績名を考えてほしいということでしょうか

**Comment by naan4UGen** [comment]
他のクイズ系と違ってヒントが出るわけではないので、

- 文字数による足切り
- 経過時間による足切り
- 累計正解数

などの方向性があると思います

自分はあんまりよく遊んでいないので難易度感が掴めておらずいい感じの境界を決めかねますが…

**Comment by Szkieletor37** [comment]
・ソートなぞなぞで遊ぶ
・5、10、15文字以上のソートなぞなぞで正解する
・5文字以上で一発正解する
など

**Comment by Szkieletor37** [comment]
経過時間、そもそも制限時間が60秒と短いのでどうなんだろうなと思うなど
難易度的にも難しい
ブザービーターはありかもしれないが

**Comment by Szkieletor37** [comment]
自明を引くガチャになりそう >経過時間

**Comment by sh-mug** [comment]
累計正解数はよさそう

文字数が多いと問題のパターンが非常に少なくなり、むしろ答えを当てやすくなるため、「N文字以上」の実績は微妙かなと思いました

**Comment by n4o847** [comment]
> 実績名を考えてほしいということでしょうか

全部です（雑）

せっかくのクイズ系 bot なので実績つけたいなとは思いつつ、自分も難易度感が掴めていない＆名前が思いつかないのでとりあえず Issue 建てて様子見しようかと

**Comment by Szkieletor37** [comment]
たしかに142だったかでナン氏が暗記チャレンジをしていたことがあったなあと思うなど >N以上

**Comment by Szkieletor37** [comment]
累計正解数、遊ばれるので良さそうな気がするが、上限を付けないと累計正解数も98で稼ぐことが可能になるのでは……？
