### ISSUE TITLE
Deprecated Web API を呼んでいる箇所を2021年2月までに殲滅する

### ISSUE THREAD

**Issue by hakatashi** [tsg-ut/slackbot#347]
`channels.*`, `groups.*`, `im.*`, `mpim.*` の Web API はすでにDeprecatedになっており、2021年2月ごろから徐々に機能を停止する予定。TSG Slackbot でも相当な箇所で呼んでいるため早めに修正する必要がある。誰か直してくれ

https://api.slack.com/changelog/2020-01-deprecating-antecedents-to-the-conversations-api

**Comment by pizzacat83** [comment]
移行先の `conversations.*` と互換性があるかというと、ない場合がある (historyなど)

**Comment by hideo54** [comment]
これもうすぐで草 (2/24)

**Comment by hideo54** [comment]
ん、しかし今ぱっと検索した感じ、残ってるのは↓だけじゃない?

`channels.invite`: channel-notifier

CODEOWNER の @hakatashi を assign しておくわね

**Comment by hideo54** [comment]
あと3日!

**Comment by cookie-s** [comment]
あと3日!

**Comment by settyan117** [comment]
2月まで、2月に入るまでの意では？

**Comment by settyan117** [comment]
ちゃんと読んでませんでした（2/24）

**Comment by cookie-s** [comment]
https://github.com/tsg-ut/slackbot/commit/304e9ab7f8bb03ecde30708ec81cb50f9fe8f06f
なんでchannels.joinじゃだめだったんだろ

**Comment by cookie-s** [comment]
たぶんchannels.joinじゃだめだった理由がわかって、

1. `channels.join` / `conversations.join`は、bot tokenの場合、`channels:join`というscopeが必要
2. `channels:join` scopeは比較的新しいscopeで、classic scopeである `bot` scopeには含まれない。
3. `channels:join` scopeを使うには、OAuthをupdateしなければならず、このときRTM APIが使えなくなって破滅する

RTMかchannels.joinを選ぶか、という感じになってしまう。
