### ISSUE TITLE
README.mdのPrerequisitesに書いてあるNode.jsのバージョンがおかしい

### ISSUE THREAD

**Issue by settyan117** [tsg-ut/slackbot#369]
https://github.com/tsg-ut/slackbot/blob/master/README.md
たぶんいま12.xで動いていると思いますが、Latestでもなければ、もはやLTSでもないので、動作環境かREADMEかどっちかを変更すべきっぽい

**Comment by settyan117** [comment]
[訂正] 12.xもLTSではあった(12.19.1)（が、それはそうとしてTSG鯖で動いているのは12.7.0でした・・・・・・）

**Comment by cookie-s** [comment]
READMEでLatest（あるいは似たような*相対的な*用語）を要求するというのは、単に、「動かねーんなら最新版にあげてから出直してこいや」の意味だと思うので、Latestにしてみて動かなかったのならコードを直すかREADMEを直すべきですが、別に修正しなくてもいいのでは、しらんけど

**Comment by settyan117** [comment]
慣れてる人ならまあいいんですが、仮にLatestで動かなくなったときに、Latestにしてみて動かねぇ～ってなった新規slackbotterがいるとぐえちゃいそう

**Comment by hideo54** [comment]
そんな文句は知らねえ、って感じだけど、「.nvmrc 置きませんか」という提案なら一考の余地はありそう (僕はなくてよくね派ですがあっても困らんし)

**Comment by hakatashi** [comment]
engines.nodeでよくない? ちなみにすでに指定してあります
https://github.com/tsg-ut/slackbot/blob/master/package.json#L14

**Comment by hideo54** [comment]
閉廷!w

**Comment by settyan117** [comment]
ほむ だとしてもREADMEに実際に動いてるバージョンを書かない理由ありますか？
slackbotをチーム開発の練習台として推してる以上、開発始めたての人に親切にすべきだと思います。たぶん慣れてるはかたしとかひでおくんの想像以上に初心者は不安です（n=1、ぼく）。

**Comment by hakatashi** [comment]
RubyやPythonと異なり後方互換性に優れたNode.jsにおいて古いバージョンにPinして動作の安定性を確保する意義は非常に低いです。READMEやpackage.jsonにおいて特定のバージョンを指定せず常に最新のバージョンが指定されるようになっているのはこの意味において古いバージョンの挙動に依存するようなコードを書いてはいけないという意思表示であり、仮に現在サーバーで動いているバージョンで正しく動かない場合、手元のバージョンではなくサーバーのバージョンをアップデートすることによって対応するべきというマニフェストを同時に指定する意味があります。なのでREADMEにLatestでない古い特定のバージョンを明示的に示すことは悪手だと思います。挙動を記述と一致させるというならそっちに合わせるのではなくサーバーのランタイムのバージョンの方をREADMEに合わせる、つまり常にLatestが使用されるようにする、という変更が考えられますが、これもNode.jsのリリースサイクルが極端に早いことを考えると現実的ではありません (もちろん理想的にはセキュリティパッチなど最新の変更は素早く適用できるようにしたいですが)。これらから僕はLatestを使うという記述を削除することには反対です。

**Comment by settyan117** [comment]
まあぼくも運用を古いバージョンに固定することは意図していません。また、常にLatestを使う運用が現実的でないのも納得です。
でしたら、その旨をREADME（or 『Slackbotを作ろう』など）に書いた上で、使用中のバージョンと併記するのはどうでしょうか。
実際のサーバーでLatestを使っていない以上、手元でLatestで動かした場合に、バージョンの不整合により動作しないことは（いくら後方互換性に優れていても）あり得ます。実際、今Latestを使うと、npm iがエラーを吐いて失敗します（これはどっちかというとnpmのバージョン/もしかしたらぼくのやりかたが悪いだけかもですが）。このような場合に、実際の動作バージョンがわかることは、原因を切り分けるための重要な情報となるのではないでしょうか。

動作バージョンをアクセスしやすい場所に記述しておくことは、Latestでの動作を保証する意思とは矛盾しないと思います。

**Comment by cookie-s** [comment]
そういうふうにローカルで失敗して原因切り分けをしたくなったときに、「サーバでの動作バージョン」を是とは考えないでほしくて、実際に「Latest」もしくはせいぜい「最近開発を行った他人の環境」をベストとして考えてほしくて、そういう意味でも「サーバの動作バージョン」を明記したくないんですよね。

ローカルでLatest試してみたらなんか動かへんのやけど
→じゃあサーバでの動作バージョンに合わせて、とあるv12.yにPINしよう　ではなく、
→オイオイLatestで動かへんのどういうことやねん、ちょっとお前動く？　となってほしい。

あるいは、
俺Latestの最高の機能でこんなきれいなプログラム書いてんけど、サーバで動かへんけど
→じゃあサーバのNodeをアップデートしましょう　にしたい。まあこれはちょっと面倒さもあるので要相談ですけど。

その意味での「Prerequisites: Latest」だと思っています。

**Comment by settyan117** [comment]
>> サーバが古いのが原因だとわかったら
サーバの動作バージョンがわからないとこれ簡単にはわからなくないですか？
具体的なバージョンを書くのがよろしくないのなら、「実際にサーバではLatestが動いているとは限らない」のようなことでも良いです。今のREADMEだと、なにも知らない人はサーバでLatestが動いていると思ってしまって、そうするとバージョン相違が問題だとは気づけないです。慣れてる人に相談するとしても、「バージョン相違の問題かも」という可能性を意識して相談する場合とそうでない場合とでは、問題解決にかかる時間も変わってくるのではないでしょうか。

**Comment by ishitatsuyuki** [comment]
3月からLatestで動いてるのでヨシ！
