### ISSUE TITLE
@tsgcat

### ISSUE THREAD

**Issue by domperor** [tsg-ut/slackbot#371]
現在，@tsgcat へのリアクションは
/better-custom-response/custom-responses.ts, l.64:        input: [/@tsgcat(?![A-Za-z])/]
によりついているようで，
/tsgcat
は全く使われていないようですが，これは意図通りの動作でしょうか？

というわけで現状 @tsgfrog とか @tsgbus みたいにしてもリアクションはつきません

**Comment by cookie-s** [comment]
> /tsgcat
これなに

**Comment by domperor** [comment]
あー，スラッシュコマンドと紛らわしい書き方ですいません
tsg-ut/slackbot/tsgcat/
あー，しかもこれforkなの，見落としてました，初歩的ですいませんでしたorz
