### ISSUE TITLE
pwnyaa: 実績が解除されない

### ISSUE THREAD

**Issue by smallkirby** [tsg-ut/slackbot#405]
pwnyaaボットでは`pwnable.xyz`及び`pwnable.tw`の半分若しくは全ての問題を解いた時にそれぞれ実績が解除されるはずですが、解除されません。悲しいね:cry:

**Comment by smallkirby** [comment]
ログを見ると、`unlock()`までは呼べていると思いますが、実績は解除されません:cry:

**Comment by smallkirby** [comment]
もう少し詳しく書きます。**想定する動作**は以下のとおりです。
- 起動時に`index.ts` (LL717)で`updateAll()`を呼び出すことで`checkAchievementsXYZ()`が呼ばれる。これは登録しているユーザの`pwnable.xyz`におけるsolve数を確認して、実績を解除する関数。
- solve数が半分以上のユーザに対して`unlock()`(LL578)が呼ばれる。
- 実績が解除されてsandboxに通知が行く。

現在の挙動は以下のとおりです。
- `checkAchievementsXYZ()`が呼ばれる。
- solve数が全完のユーザ、例えばsmallkirbyに対してLL576の条件が満たされるため、`if`文の中に入る。
- `logger.info('[+] pwnyaa: unlocking: pwnyaa-xyz-complete');`が実行されてログが出るところまでは本番サーバで確認した。
- `unlock()`で実績が解除されない。

ローカル環境においては以下のようにログが出ます。
```
{"message":"[+] pwnyaa: checking achievements for XYZ...","level":"info","timestamp":"2021-02-17T11:07:18.715Z"}
{"message":"[+] pwnyaa: unlocking: pwnyaa-xyz-complete","level":"info","timestamp":"2021-02-17T11:07:23.425Z"}
<SlackID> unlocked pwnyaa-xyz-complete, undefined
{"message":"[+] pwnyaa: unlocking: pwnyaa-xyz-half","level":"info","timestamp":"2021-02-17T11:07:23.426Z"}
<SlackID> unlocked pwnyaa-xyz-half, undefined
```

**Comment by smallkirby** [comment]
上記の`<SlackID>`はスラックのユーザID(上の例だとsmallkirbyのslackID)になっています。
これを使って`getMemberName()`で名前を取得することはできています。

**Comment by cookie-s** [comment]
今pwnyaaがachievementsが動いてない方のサーバで動いてるので、achievementsのモジュールが初期化されて無くて、
https://github.com/tsg-ut/slackbot/blob/master/achievements/index_production.ts#L51
ここにたどり着いてないですね〜

**Comment by smallkirby** [comment]
なるぽよ :bow:

**Comment by cookie-s** [comment]
pwnyaaをachievementsが動いてるサーバの方に移しました。
加えて、
`pwnyaa/state.json` と、
```
PWNABLE_TW_USERNAME
PWNABLE_TW_PASSWORD
PWNABLE_XYZ_USERNAME
PWNABLE_XYZ_PASSWORD
CHANNEL_PWNABLE_TW
```
もコピーしました。
解決！

**Comment by smallkirby** [comment]
ありがとうございます！！！！！！！！！！！！！！！！！！！！！！！！！！！！！！！！！！！！！！！
