### ISSUE TITLE
pwnyaa: scrapeitによる問題カウントのバグ

### ISSUE THREAD

**Issue by smallkirby** [tsg-ut/slackbot#422]
`fetchGenresCH()`でcryptohackから問題を取ってくる時に、各ジャンルの各大問において最初の問題しかパースされていない。
多分あとで自己solveしますが、忘れないようにissue建てとこ。

**Comment by smallkirby** [comment]
@hakatashi お手数ですが、未修正時に誤って解除されたくっきーさんの実績2つ(`pwnyaa-ch-half`と`pwnyaa-ch-complete`)を削除して頂けますか:bow:。(削除のプロセス等わからないためhakatashiさんに頼むのが正解かわかりませんが...)

**Comment by smallkirby** [comment]
追加でしとおさんの`pwnyaa-ch-half`もお願いします:bow: :bow: : bow:

**Comment by hakatashi** [comment]
@smallkirby 対応しました。

achievementsのDBをいじるためのスクリプトは `achievements` ディレクトリ配下にあります。今回achievement単位での削除のため `remove-achievement.js` を追加しました。以降は本番環境でこれを叩くとかして対応してください。

```sh
npx ts-node achievements/remove-achievement.js [user] [achievement]
npx ts-node achievements/normalize.js
```

**Comment by smallkirby** [comment]
ありがとうございます！！ :bow:
