### ISSUE TITLE
Legacy bot から脱却する

### ISSUE THREAD

**Issue by hideo54** [tsg-ut/slackbot#424]
今 TSG が使っている bot token は実は legacy.

単純に新しいやつ使いたいねというだけでなく、Slack SDK を使って綺麗に書ける部分が増えるし、今後どんどんサポートが切られていく可能性もあるので、ぜひとも移行しておきたい。
ただし、既存のテストを書き換える必要もあったりと、いささか面倒かも。そこのテストを諦めるという手もなくはないが。

ついでに HAKATASHI_TOKEN も USER_TOKEN とかわかりやすい名前に変えたい…変えたくない?

参考資料:
* Legacy bot について: https://api.slack.com/legacy/custom-integrations/bot-users
* Slack の token の種類: https://api.slack.com/authentication/token-types

**Comment by pizzacat83** [comment]
Legacy tokenを使っている理由はRTM APIが使えるというのが大きいと思っているのですが、最近[Socket Mode](https://api.slack.com/apis/connections/socket)という新生RTM API的なやつが出たのでそれを使うことで新しいtokenに移行できるかもしれません。(詳しく調べていないので、RTM APIの代用になるかはわかりません。)

**Comment by cookie-s** [comment]
なんかあとで精査が必要な文章
> In our newer bot guide we do suggest that you use the Events API with bots in Slack apps; however you can also continue to use the Real Time Messaging API that was suggested for use with legacy bots.

**Comment by pizzacat83** [comment]
お、マジ

**Comment by pizzacat83** [comment]
>New Slack apps may not use any Real Time Messaging API method. Create a classic app and use the V1 Oauth flow to use RTM.
https://api.slack.com/rtm

まあ試してみるのが確実そうです

**Comment by pizzacat83** [comment]
いや、よく考えると上は「今後作成するApp」に対する主張ですね

**Comment by cookie-s** [comment]
NewとClassicとLegacyな何かがあるのではという予想です（Slack、なんかドキュメントとか用語が一貫してるイメージはないので、こまる）

**Comment by cookie-s** [comment]
ちょっとこれやってみたいです。

想定手順です:
* slackbot2というSlack appをとりあえず(自分だけで)作ってみる
  * 個人workspaceにひもづける
* sushi-botをとりあえず個人workspaceで動くようにする
* --onlyをつかって、前にtsgbotを2鯖で動かしてたときみたいに、sushi-botだけとりあえずtsgでもslackbot2で動かしてみる
* ちょっとずつがんばる

**Comment by hakatashi** [comment]
かなりよさそう。お願いします

**Comment by cookie-s** [comment]
まず、RTMが使える"Classic App"は
https://api.slack.com/rtm#classic
にあるリンク `https://api.slack.com/apps?new_classic_app=1` から現在でも作成可能。

**Comment by hideo54** [comment]
TSG の slackbot で RTM 使ってるのってほとんどメッセージ受信なので、雑に message event 受け取るサーバーを建てて (fastify plugin にするといいかな?)、そのへんまとめて移行したい気持ちあるなあ

**Comment by cookie-s** [comment]
俺はEvents APIはまだ考えてないぞ、Socket Modeができたらそれでとりあえず一回話を終わらせるからな

**Comment by hideo54** [comment]
オイオイオイ
Events API でええやん…よくない?

**Comment by cookie-s** [comment]
だってSocket Modeのほうが楽そうじゃない？少なくともぱっと見。

**Comment by hideo54** [comment]
まあちょっとわかるんですが、一つは、Socket Mode ってまだそこまで成熟したものであるイメージがないんですよね (これは僕のキャッチアップ不足な気もする)。加えて…

## 移行コスト

> Socket Mode is only available for apps using new, granular permissions. If you created your app on or after December of 2019, good news: your app already uses the new permissions. Otherwise, you may have to migrate your classic Slack app to use granular permissions before turning on Socket Mode.
https://api.slack.com/apis/connections/socket

とありますが、

> New Slack apps may not use any Real Time Messaging API method. Create a classic app and use the V1 Oauth flow to use RTM.
https://api.slack.com/rtm

とあるとおり、RTM から完全離脱しないと Socket Mode は使えません。別 bot にするのも手間じゃないですか?

## [Node Slack SDK](https://github.com/slackapi/node-slack-sdk) に含まれていない

Socket Mode を使うためには、今 Slack さんが激推ししてる Bolt を使うことになり、現 SDK と競合しうるので手間になります。
……まあ、かたや Node Slack SDK は安泰かというと、

> ### **Deprecation Notice**
> _`@slack/events-api` and `@slack/interactive-messages` officially reached EOL on May 31st, 2021. Development has fully stopped for these packages and all remaining open issues and pull requests have been closed._
> _At this time, we recommend migrating to [Bolt for JavaScript](https://github.com/slackapi/bolt-js), a framework that offers all of the functionality available in those packages (and more). To help with that process, we've provided some [migration samples](https://slack.dev/node-slack-sdk/tutorials/migrating-to-v6) for those looking to convert their existing apps._
https://github.com/slackapi/node-slack-sdk#deprecation-notice

とあり、どちらにしろ Bolt への移行は避けられないのですが…

## Events API と Socket Mode の違いはほとんどない

> In Socket Mode, your app still uses the very same Events API and interactive components of the Slack platform. The only difference is the _communication protocol_.
https://api.slack.com/apis/connections/socket#overview

「ほとんどないなら public HTTP endpoint を建てる必要がない Socket Mode の方がよいじゃん」という見方ももちろんあるりますが、上述の理由から、とりあえず Events API を使っておいて、RTM を駆逐できたら Socket Mode に移行する、という流れでいいんじゃないかと思います。その移行は (_the very same_ を信用するなら) 比較的楽そう。

**Comment by cookie-s** [comment]
まず、Issueのタイトルは「Legacy botから脱却する」です。私はこれを、Legacy Appでなくすることと捉えました。そしてその際に問題になるのがRTMですから、RTMを脱却することがほぼこのIssueのゴールと捉えています。

node-slack-sdkにsocket-modeは含まれています。単純にドキュメント不足なんだと思います。
https://www.npmjs.com/package/@slack/socket-mode

Legacy botでなくなり、New Slack appとすることによって、最新のSlackのdocがまともに機能するようになります。たとえば、Slack docのpermissionなどは、New Slack app向けにかかれており、Legacy Appのためには適宜読み替えたりしないといけないという認識です。

**Comment by cookie-s** [comment]
> Events API と Socket Mode の違いはほとんどない

のであれば、(僕の中ではおそらく、くらいの確信度で)移行が容易なSocket Modeにしてから、Events APIに移行しよう、という手順で良いかと思います。
もちろん、Socket Modeが最終形として一番良いかはしらなくて、Events APIがSlackの推しであることは認識しています。勝手な予想ですが、Slackが、RTM勢がなかなか移行してくれないから用意したのがSocket Modeと思っていて、そうなのであればこれに乗るのがベターと考えています。まあ手順が長くなるんで、ぱっとEvents APIにしてくれる人がいればしてくれればいいんですが、このIssueは一年までではないですが放置されています。

**Comment by hideo54** [comment]
oh, これはこれは…すいません。 > @slack/socket-mode

仰ることはすべて同意です。それがゴールです。その上で今、ゴールにたどり着くまでの間の経路のとり方について、主に実装コストの観点で話していました。段階的な移行ができる Events API の方が、すべて RTM を駆逐し終えてからでないと達成できない Socket Mode よりも楽に作業できるのではという話です。

> このIssueは一年までではないですが放置されています

これは本当にそのとおりで、結局じゃあ hideo54 はやるんかいとなると多分やらないので、最終的には作業のやる気のある人の判断でよいと思います

**Comment by cookie-s** [comment]
なるほどね　かなりEvents APIとかSocket Modeとかnode-slackのことがわかってきて、Socket Modeじゃなくていい気がしてきました　ありがとうございます
もうちょっとがんばります

**Comment by cookie-s** [comment]
え、これもしかしてめちゃくちゃやるだけ？

**Comment by hideo54** [comment]
プロ

**Comment by cookie-s** [comment]
まずは簡単 (`rtm.on('message', `くらいしかなさそう)なものから。
テストってえらいな～

**Comment by cookie-s** [comment]
ちなみにcommit push script
<details>

```
#!/bin/sh

dirs="ahokusa \
        anime \
        atcoder \
        better-custom-response \
        checkin \
        context-free \
        dajare \
        emoji-modifier \
        emoxpand \
        golfbot \
        hakatashi-visor \
        hangman \
        hayaoshi \
        kirafan \
        lyrics \
        mahjong \
        octas \
        pocky \
        ponpe \
        pwnyaa \
        room-gacha \
        sorting-riddles \
        summary \
        sunrise \
        taiko \
        tiobot \
        vocabwar \
        voiperrobot \
        wordhero \
        "


for dir in $dirs
do
    git checkout master
    git checkout -b $dir-deprecate-rtm
    git add $dir
    git commit -m "$dir: deprecate rtm"
    git push origin $dir-deprecate-rtm
done
```

</details>

**Comment by hideo54** [comment]
大変お疲れさまです。それぞれ数が多い中ご対応くださりありがとうございます。
Draft 以外の (Open or Merged の) 関連する Pull Request にすべて目を通し、レビューしました。

Events API, 割とこれまで通りに見えて、ちょっと来るデータ構造変わってたりします。レビューにおいて、`thread_ts` と `username` の2点が気になったので、それら2点が使われているものについては、次の通りコメントして request changes しました。

```
実験してないのでもし実際に来てたら申し訳ないのですが、ドキュメントを読んだ限りでは、`message.thread_ts` は来ない気がしています (`message.message.thread_ts` または `message.message.ts` になる気がする)。間違ってたらすいません。実験しましょう。
https://api.slack.com/events/message/message_replied
```

```
実験してないのでもし実際に来てたら申し訳ないのですが、ドキュメントを読んだ限りでは、`message.username` は来ない気がしています。間違ってたらすいません。実験しましょう。
https://api.slack.com/events/message
```

その他はそのまま引き継げると思いますので、accept しました。

横からしゃしゃり出て申し訳ないのですが一助になればと。これもし問題なかったら申し訳ねえな。よろしくお願いします。

**Comment by hideo54** [comment]
特に thread_ts については、undefined になってしまっていたら即機能不全になってしまう気がします。これが使われていてかつ merge 済みのものは、#594, #599 です。ちゃんと動いているか確認してみたいですね。

**Comment by hideo54** [comment]
ちなみに、完全に手前味噌ですが、channel notifier については、僕の管理している Slack では既に Events API 化していますので、ぜひご参照ください。結構構造変わっています。
https://github.com/hideo54/psi-slack/blob/main/channel-notifier.ts

お前が PR 出せやという声が聞こえて来そうだな。すいません。暇なときやります。

**Comment by cookie-s** [comment]
```
eventClient.on('message', (message) => {
    console.log({message})
});
```
```
{
  message: {
    client_msg_id: '8c2a7e2b-b900-4fad-8a02-xxxxxxxxxxxxxx',
    type: 'message',
    text: 'ほげ',
    user: 'Uxxxxxxx',
    ts: '1641265473.000300',
    team: 'Txxxxxxxx',
    blocks: [ [Object] ],
    thread_ts: '1641265458.000200',
    parent_user_id: 'Uxxxxxxxx',
    channel: 'Cxxxxxxxx',
    event_ts: '1641265473.000300',
    channel_type: 'channel'
  }
}
```

閉廷！ｗ

**Comment by cookie-s** [comment]
usernameはしらん

**Comment by cookie-s** [comment]
https://github.com/slackapi/node-slack-sdk/blob/main/packages/web-api/src/response/ConversationsHistoryResponse.ts#L53
このへんですかね

**Comment by cookie-s** [comment]
```
{
  message: {
    type: 'message',
    subtype: 'bot_message',
    text: 'ｼｭｯｼｭｯ (起動音)',
    ts: '1641266332.000700',
    username: 'tsgbot [DESKTOP-UXXXXX]',
    bot_id: 'Bxxxxxxxx',
    channel: 'Cxxxxxxxx',
    event_ts: '1641266332.000700',
    channel_type: 'channel'
  }
}
```
usernameもきたわ

**Comment by cookie-s** [comment]
https://github.com/slackapi/java-slack-sdk/blob/master/json-logs/samples/api/channels.history.json
こういうのもあるらしいです

**Comment by hideo54** [comment]
このドキュメントホンマ……

**Comment by kurgm** [comment]
`username` は人間の投稿にはつかなくて、bot の投稿の中でも `chat.postMessage` するときに `username` `icon_emoji` `icon_url` のうち 1 つ以上を設定した投稿にだけつくみたいですね

ちなみに、さっき実験してるときに分かったこととして、 `username` `icon_emoji` `icon_url` を設定して `chat.postMessage` するためには (classic apps でない場合) `chat:write.customize` とかいうスコープが追加で必要になるっぽいので、雑な例だったらついてなくても、まあ、みたいなところはあるかもしれない（？）
このへん参照: https://api.slack.com/methods/chat.postMessage#authorship

**Comment by hideo54** [comment]
なるほどなあ 実験ありがとうございます :bow:
またしてもやってしまったきつねさん (ごめん…)

**Comment by cookie-s** [comment]
かんたんなのは終わって、続きをちょっと気をつけてやっていくよ

**Comment by cookie-s** [comment]
残り

- tunnel
- lib/slack.ts
- lib/slackUtils.ts
- lib/slackMock.js, index.ts, package.json
