### ISSUE TITLE
コマンドラインオプションの--onlyがかぶると、起動に死にがち

### ISSUE THREAD

**Issue by cookie-s** [tsg-ut/slackbot#425]
index.jsの機能で、--only deployなどとするとdeploy botのみを起動し、--only deploy --only sushi-botなどとすると2つだけを起動できるが、--only deploy --only deployなどとするとdeployを2つ起動しようとする。

deployの場合は、同じメソッド・同じパスのhttp handlerをfastifyに登録しようとするため、http serverが立たなくなる。
他のbotの場合も、たいていは2重起動について考慮していないから、なにかしらおかしいことが起きがちと思われる。

index.js内で、pluginsに対してuniqをとるとか、二重登録があったらassert falseして全体を終了するとか、そういうことを考えてもいいかもしれない。

現状のエラーメッセージ
```json
{"message":"AssertionError [ERR_ASSERTION]: Method 'POST' already declared for route '/hooks/github'\n    at Router._insert (/home/slackbot/slackbot/node_modules/find-my-way/index.js:304:9)\n    at Router._on (/home/slackbot/slackbot/node_modules/find-my-way/index.js:197:8)\n    at Router.on (/home/slackbot/slackbot/node_modules/find-my-way/index.js:74:8)\n    at Object.afterRouteAdded (/home/slackbot/slackbot/node_modules/fastify/lib/route.js:241:16)\n    at /home/slackbot/slackbot/node_modules/fastify/lib/route.js:175:25\n    at Object._encapsulateThreeParam (/home/slackbot/slackbot/node_modules/avvio/boot.js:545:7)\n    at Boot.timeoutCall (/home/slackbot/slackbot/node_modules/avvio/boot.js:447:5)\n    at Boot.callWithCbOrNextTick (/home/slackbot/slackbot/node_modules/avvio/boot.js:428:19)\n    at Boot._after (/home/slackbot/slackbot/node_modules/avvio/boot.js:273:26)\n    at Plugin.exec (/home/slackbot/slackbot/node_modules/avvio/plugin.js:131:17)","level":"error","timestamp":"2021-02-28T06:23:20.511Z"}
```

**Comment by kom-bu** [comment]
あえて二重にロードしたい人がいるかもしれないという立場で「二重登録があったら警告レベルのログを出した上でuniqを取らずに続行」という方針も考えられるんでしょうか（よくわかりません……）？その場合、現行のローディングメッセージが二重登録を考慮していないので、そこも変える必要がありますが。

**Comment by settyan117** [comment]
二重ロードしたいひと、いる？

**Comment by cookie-s** [comment]
「`--only` が1つも指定されていなければ全部が1つずつ起動する。それが嫌なので `--only` というオプションが追加され、いくつかのbotに起動を制限できるようになった。」という背景と考えているため、二重起動したいひとが仮にいたとして、それを `--only` という名前のオプションに求めるのは筋違いだろうと思っています。

**Comment by kom-bu** [comment]
「二重登録があったら警告レベルのログを出した上でuniqを*取って*続行」というのは考えられますか

**Comment by cookie-s** [comment]
> index.js内で、pluginsに対してuniqをとるとか、二重登録があったらassert falseして全体を終了するとか、そういうことを考えてもいいかもしれない。

これの前案「pluginsに対してuniqをとるとか」はそれを想定していました。

**Comment by settyan117** [comment]
勝手に解決して実行するなら「警告レベル」は適切ではないのでは？（単に「まとめます」くらいのメッセージとか、ぶっちゃけ何も出さなくてもいいかなぁともおもう）

**Comment by cookie-s** [comment]
I don't have strong opinion.
