### ISSUE TITLE
AmongUsボットの案

### ISSUE THREAD

**Issue by smallkirby** [tsg-ut/slackbot#436]
AmongUsのやる気ある人を集めるBOTの案出しです。他に案がある場合は教えてください。原案はhideoさんですが、今の所僕が実装しようかと思っています。

# 主な機能
- 「今から何時間以内」に「どれくらいの確度」でやる気があるかを登録できるようにする。
  - 時間を過ぎたら勝手に除外される
- 規程人数に達したら登録した人にメンションする
  - 確度に応じて人数のカウントを変える

# 使用するチャンネル
- #sig-among-us

# 考え中
- 「今から何時間以内」と「何時〜何時」のどちらで登録するか
- 確度による人数カウントをどう計算するか

**Comment by Szkieletor37** [comment]
わがままなので「2Imposterならやりたい」みたいな希望を出せるとうれしいになってしまった

**Comment by hideo54** [comment]
いいですね〜〜〜〜 担当ありがとうございます :bow:

> 「今から何時間以内」と「何時〜何時」のどちらで登録するか
わがままなので両方あるといいんじゃないかと思いました

> 確度による人数カウントをどう計算するか
僕は確度を提案していないのでなんとも言えない (要る?)

わがままな提案ですが、Block Kit の component を使った UI だと泣いて喜びます https://api.slack.com/block-kit/interactivity
…が、サーバー建てるのめんどかったらリプライ方式でもいいと思います

**Comment by smallkirby** [comment]
頂いた案を受けて、取り敢えず以下の感じで作ろうと思います。
- UIはBlockKitを使う
- 募集の開始・終了はSlash commandを使う
- 選択事項は「希望時刻」と「最低希望人数」にして、「確度」は扱わない
  
今の所のイメージは以下のような感じです。
![Screenshot from 2021-03-27 19-23-33](https://user-images.githubusercontent.com/47111091/112717807-37aaa880-8f32-11eb-874f-e0eb0eebf3e6.png)
