### ISSUE TITLE
たほいやのdeployブロックが長い

### ISSUE THREAD

**Issue by cookie-s** [tsg-ut/slackbot#472]
deploy block、主にたほいやのために作ったけど、麻雀とかならまだしも、よく考えたらたほいやが再起動に耐えるように実装されるべきじゃないですか？

https://github.com/tsg-ut/slackbot/pull/65
https://github.com/tsg-ut/slackbot/pull/211

**Comment by cookie-s** [comment]
smallkirbyくんもきっとそういっています

**Comment by smallkirby** [comment]
え、えーっと。。。。。。。。。。そうだそうだ！！！！！！！！！！！！！

**Comment by smallkirby** [comment]
誰もやらなければ僕がやろうと思います

**Comment by cookie-s** [comment]
え、最近めっちゃslackbotにcommitするやん、えら
