### ISSUE TITLE
hangmanで!によるguessに失敗すると入力を受け付けなくなるっぽい

### ISSUE THREAD

**Issue by Szkieletor37** [tsg-ut/slackbot#478]
https://slack-log.tsg.ne.jp/thread/1619588335.069200?ts=1619588345.071500
再現性あるんかな

**Comment by Szkieletor37** [comment]
https://slack-log.tsg.ne.jp/thread/1619566584.349800?ts=1619566606.352100

**Comment by Szkieletor37** [comment]
なぜかパーフェクト判定も出ている

https://slack-log.tsg.ne.jp/C7AAX50QY/1619588575.100300

**Comment by Szkieletor37** [comment]
@smallkirby 
https://github.com/tsg-ut/slackbot/blob/441824269f1da45ec8f016290309dcca46471978/hangman/index.js#L231
クリア判定も条件に入れないと無回答タイムオーバーでも褒められてしまいます

**Comment by smallkirby** [comment]
うお、報告ありがとうございます。
今週ちょっときつそうなので、来週あたり時間ある時に治します:bow:
