### ISSUE TITLE
博多氏おらん時に早押しクイズ終わらん

### ISSUE THREAD

**Issue by smallkirby** [tsg-ut/slackbot#485]
えい、えい、むん！

**Comment by smallkirby** [comment]
これ何のことか忘れちゃった

**Comment by JP3BGY** [comment]
全員が突然やる気をなくしたら早押しが永遠と問題文と答えを読み連ねるって話じゃないの？

**Comment by smallkirby** [comment]
や、多分博多氏作の問題出たけど博多氏おらんっていう時に他の人が全滅すると、作問ポイント入ってるから問題は続いて5問待つしかないみたいな感じだった気がする
