### ISSUE TITLE
discord: 複数コマンドのワンライン指定

### ISSUE THREAD

**Issue by smallkirby** [tsg-ut/slackbot#508]
できたらいいね、大塚製薬
```.sh
!play https://nirugiri.smallkirby.xyz shuffle repeat
```

**Comment by settyan117** [comment]
#sandybox の MusicBot は https://github.com/jagrosh/MusicBot をslackbotとは独立に動かしているので、これをforkなりしてissue立てると良いと思います

**Comment by settyan117** [comment]
https://github.com/tsg-ut/MusicBot
