### ISSUE TITLE
Discord TTS: 外部APIのレスポンス待ちで読み上げのクエリが詰まる

### ISSUE THREAD

**Issue by Yosshi999** [tsg-ut/slackbot#530]
https://github.com/tsg-ut/slackbot/blob/d060440b255ccefa84b3382b7fd1f08abedc78a0/discord/tts.ts#L156

voicevoxのAPIが時々重い（例：初回起動時）のですが、そのときmutex内のgetSpeechで止まってしまい後続の他の人の読み上げも詰まってしまう

選択肢

* voicevoxのttsのときはクエリが飛ぶ前に叩いて起こしておく（もしくはtts起動中定期的にpingを飛ばす）
  - pros: レスポンス自体が早くなるのでvoicevox声帯の使用者も嬉しい
  - cons: コードが複雑化・APIサーバーの課金時間増加(多分軽微)
* mutexを外す
  - pros: 実装がらく
  - cons: discordの投稿順と発声の順序がずれる・その他race conditionの考慮が必要

**Comment by JP3BGY** [comment]
発生の順序はずれてもよさそうだけど、そもそも何のためのmutexなんやろ。

**Comment by Yosshi999** [comment]
start/quit/voice変更時にリスト操作とか（voice status変更時はDBも？）が走ってるので、ここらへんで競合するとなにかまずいことが起こるような気がします。
発声だけmutexを外すという手も？

**Comment by JP3BGY** [comment]
外部APIの部分だけは明らかにmutexいらないしそこだけ外すってのは無理かな

**Comment by hakatashi** [comment]
TTSにmutexが入ってるのはDiscordに音声を流す際に前の音声が終了してないと中断して次のが流れてしまうためです。
Discordに流す以外の部分をmutex外すのは全然ありです

**Comment by Yosshi999** [comment]
tempファイル書き出しと再生のところだけをmutexで包むってことですかね？
https://github.com/tsg-ut/slackbot/blob/master/discord/tts.ts#L281-L293
