### ISSUE TITLE
pwnyaa: 問題を解いた年月が正しく表示されないバグ

### ISSUE THREAD

**Issue by iwashiira** [tsg-ut/slackbot#554]
pwnable.xyzの2021年11月に解いた問題が2020年12月に解いたとして表示される。
2021年8月以前に解いた問題は正常な年月が表示されている。

**Comment by smallkirby** [comment]
僕がTwiterのID変えたことによるバグでした :kusa:

**Comment by smallkirby** [comment]
あ、違う、これはこの話じゃないや
