### ISSUE TITLE
deprecate rtm.start 

### ISSUE THREAD

**Issue by cookie-s** [tsg-ut/slackbot#555]
なんかメール来た

```
 Updates required for those still using rtm.start
 
 Hello Slack Developer,
 
 As a contributor or owner of tsgbot that recently used the rtm.start Web API method, we wanted to inform you about two important changes coming to rtm.start :
 
 November 30, 2021
 New Slack apps and integrations will no longer be able to use rtm.start and must use rtm.connect instead.
  
 
 September 20, 2022
 The response from rtm.start will transform into the brief response found in the method that replaces it, rtm.connect.
 While the RTM API will remain unchanged, we do encourage you to migrate to modern Slack apps and Socket Mode instead.
```

rtm.startをrtm.connectにしとくとよさそう

https://api.slack.com/methods/rtm.start

**Comment by cookie-s** [comment]
よく見たらキリ番じゃん

**Comment by hakatashi** [comment]
踏み逃げ禁止!

**Comment by hideo54** [comment]
もしかして

* https://github.com/tsg-ut/slackbot/blob/4070b6d100e5dc9b35ce6d9046f865f659490182/lib/slack.ts#L47
* https://github.com/tsg-ut/slackbot/blob/4070b6d100e5dc9b35ce6d9046f865f659490182/lib/slack.ts#L62

を書き換えるだけじゃない?

**Comment by cookie-s** [comment]
今別件で見てたら、

https://slack.dev/node-slack-sdk/rtm-api
> ## Lifecycle events
> ...
> authenticated | (connectData) - the response from rtm.connect or rtm.start | The client has authenticated with the platform. This is a sub-state of connecting.
> -- | -- | --

ここちょっと壊れるかも
https://github.com/tsg-ut/slackbot/blob/6427df832041e0b21de02f31603b2ac2f5fe5c90/index.ts#L196-L197

**Comment by cookie-s** [comment]
や、これくらいは返してくれるっぽい
