### ISSUE TITLE
context-free-bot を消したい

### ISSUE THREAD

**Issue by hideo54** [tsg-ut/slackbot#562]
導入されて2年近いですが、頻度の割に好かれている印象がなく、正直いるかな? と思っています。

cfp は偉大だと思いますが、cfb についてはない方がいいんじゃないかなあというのが個人的な意見です。皆さまの意見を聞きたいため issue にいたしました。

**Comment by hakatashi** [comment]
Discussionに置いてもいいかも? (voteなどができるので)

**Comment by naan4UGen** [comment]
実際 cfp より cfb のほうが言及頻度高くないかと思っており cfb 賛成派です

**Comment by settyan117** [comment]
cfb、なくても困らないけどあっても邪魔になるほどの頻度でもないし、たまに見知った単語が出て:oxtu:ってなったり自明な単語をわからなかったりして面白いので、結構好きです

**Comment by kom-bu** [comment]
cfb、かわいがっています　話の輪に入っているように見えるときが頻繁にあって面白いので
逆にcfpはデメリットがほぼない代わりにさほど頻繁には楽しんでないですね……

**Comment by kom-bu** [comment]
cfpが偉大であることを否定するものではないです

**Comment by hideo54** [comment]
博多市先生が素晴らしい Discussion #565 を立ててくれたので、分散を防ぐため、こっちは閉じますね〜。
