### ISSUE TITLE
Discord (TTS, hayaoshi): TTSの再生が割り込まれる / 再生終了時イベントの捕捉方法について

### ISSUE THREAD

**Issue by Yosshi999** [tsg-ut/slackbot#570]
## Overview
discord ttsの再生が割り込まれるバグがあり、discord botが再生を終了する前にmutexから抜けてしまっているのではないかと疑っています。

音声リソース `resource` をdiscord botに再生させ、その再生の終了を検知したいときに、 `resource.playStream.on` でリソースの読込ストリームの `finish` イベントを利用している(example: https://github.com/tsg-ut/slackbot/blob/d5c8870681e5d24892f34c1e93f6d4b8afc0a1bc/discord/tts.ts#L316-L318 )が、これについて言及しているドキュメントがあれば教えてください

## 再現
1. 長い文字列をTTSに喋らせる
2. botが喋っている途中で新しい文字列を喋らせる
→ 1.で再生中の文章が中断される

## 修正方針？
[公的なドキュメント](https://discordjs.guide/voice/life-cycles.html#subscribing-to-individual-events)だと `enterState` を使っているようなので、こちらに切り替えて症状が改善するか見てみたい

**Comment by cookie-s** [comment]
AudioPlayerとは、discordjs内の、playerであり、再生を管理している。Idleであったり、何かしらのAudioResourceを再生中だったりする。

AudioResourceとは、discordjs内で作成される、「音楽リソース」である。

AudioResource.playStreamとは、prism-media ([gh](https://github.com/amishshah/prism-media), [doc](https://amishshah.github.io/prism-media/?api#core.FFmpeg))のインスタンスである。
https://github.com/discordjs/voice/blob/9c924834dd7b3de5f5f3f09c3b2a5f5695024403/src/audio/AudioResource.ts#L4
今回、createAudioResourceの引数はstring[なので](https://github.com/tsg-ut/slackbot/blob/d5c8870681e5d24892f34c1e93f6d4b8afc0a1bc/discord/tts.ts#L314), prism.FFmpegが使われる[気がする](https://github.com/discordjs/voice/blob/9c924834dd7b3de5f5f3f09c3b2a5f5695024403/src/audio/TransformerGraph.ts#L140-L150)。prism.FFmpegは、stream.Duplexのextends[である](https://github.com/amishshah/prism-media/blob/7071332df596cb04ecf06d9c8e8521b89fec0aab/src/core/FFmpeg.js#L22)。Duplexには'finish'というイベントが[定義されており](https://nodejs.org/api/stream.html#event-finish)、これは

> after the stream.end() method has been called, and all data has been flushed to the underlying system.

を意味する。

ちなみに、playStream.on('finish')の使用事例はこのへん？
https://github.com/discordjs/voice/blob/7e493c77c379da5629d9218c57589d89f94bd5c5/src/audio/AudioPlayer.ts#L408-L412

**Comment by cookie-s** [comment]
実際に、finishがやってくるのは、prismがsubprocessとして起動したffmpegのprocessのstdin。 https://github.com/amishshah/prism-media/blob/7071332df596cb04ecf06d9c8e8521b89fec0aab/src/core/FFmpeg.js#L51-L71

**Comment by Yosshi999** [comment]
ここのcallback
(https://github.com/discordjs/voice/blob/7e493c77c379da5629d9218c57589d89f94bd5c5/src/audio/AudioPlayer.ts#L388-L398)

を見ると、 `finish` 時はあくまでBuffering stateになった時点(つまり音声バイナリが主プロセスの管理するメモリに載ったとき)で発火されており、その後この `onReadableCallback` を介して Playing stateになり、再生が完了したらIdle stateに戻る？

**Comment by Yosshi999** [comment]
割り込みは起こりえないがdiscordの早押しクイズにも同じような記述がある。
https://github.com/tsg-ut/slackbot/blob/6427df832041e0b21de02f31603b2ac2f5fe5c90/discord/hayaoshi.ts#L258
https://github.com/tsg-ut/slackbot/blob/6427df832041e0b21de02f31603b2ac2f5fe5c90/discord/hayaoshi.ts#L328

前者は問読み(readQuestion)の内部だが、途中で問読みが黙ってしまうバグとは関係ないように思える(これってもう直ってたっけ？)

**Comment by cookie-s** [comment]
たしかに。ffmpegはエンコードを終了しちゃったら終わる気がするので、finishよりも、endのほうがよさそう。

**Comment by cookie-s** [comment]
> 公的なドキュメントだと enterState を使っているようなので、こちらに切り替えて症状が改善するか見てみたい

Idleになるのは、Playerなので、どっちかって言うと今のresourceのeventで動くほうが筋がいい気はする。

**Comment by cookie-s** [comment]
なおったんかな

**Comment by hakatashi** [comment]
discord/hayaoshiがまだ

**Comment by cookie-s** [comment]
ttsはなおったんかな hayaoshiはむずかしいんかな

**Comment by Yosshi999** [comment]
ttsは多分直りました　早押しはそこまで直すモチベーションがなさそう
閉じちゃった方がいいですか？
