### ISSUE TITLE
topic が時々 thread の親を読む

### ISSUE THREAD

**Issue by hideo54** [tsg-ut/slackbot#647]
ある投稿のスレッドにつけられた投稿が5これすきを集めたとき、その投稿の文ではなく、親投稿の文が topic に採用されることがある。

常に再現しているわけではない気がする。ぱっとコードを見て「わかんないね〜」と先日博多市と話しました。

**Comment by Szkieletor37** [comment]
`slack.conversations.history` で返す内容を確認しましたが、チャンネル本体にも投稿されているメッセージしか返さないようなので、「以下のチャンネルにも投稿する」にチェックがない（スレッドのみに投稿されている）メッセージにリアクションが付いた場合、そのスレッドのうち最も新しい、チャンネルにも投稿されているメッセージが返り、それが採用されるということのようです。

**Comment by Szkieletor37** [comment]
↑スレッド内のみの投稿を採用しないのは仕様ということで、このissueは「broadcastされている投稿に5koresukiがついた場合でも、その親のメッセージがtopicに採用されてしまう場合がある」らしい
