### ISSUE TITLE
sushi-botがフムフムヌクヌクアプアアに対応していない

### ISSUE THREAD

**Issue by cookie-s** [tsg-ut/slackbot#649]

**Comment by hakatashi** [comment]
要件: 「フムフムヌクヌクアプアア」を含むメッセージに :humuhumu-nukunuku-apua'a: リアクションをつける

**Comment by cookie-s** [comment]
きづいたけどこれsushi botじゃないわ bcrだわ

**Comment by cookie-s** [comment]
まあどっちでもいいわ

**Comment by cookie-s** [comment]
https://github.com/tsg-ut/slackbot/pull/295
