### ISSUE TITLE
Legacy bot から脱却する2

### ISSUE THREAD

**Issue by cookie-s** [tsg-ut/slackbot#679]
#424 の続き

Legacy botじゃなくてなんか新しいAppにする。Permissionとかを見直す

**Comment by hakatashi** [comment]
ところで slack-patron がまだ RTM API 使ってるかも？

**Comment by cookie-s** [comment]
おなじtokenだっけ

**Comment by hakatashi** [comment]
確認したけど同じAppの bot token を使ってるっぽい

**Comment by cookie-s** [comment]
https://github.com/tsg-ut/slack-patron/issues/27
リンク張っとこ

**Comment by cookie-s** [comment]
とりあえずslack-patronのRTM止めてきたぜ

**Comment by cookie-s** [comment]
ほな、Legacyじゃないbotにアップグレードする準備させてもらいます

**Comment by cookie-s** [comment]
無事終えました。bot tokenも基本的権限を得ました、やったね

**Comment by hakatashi** [comment]
Super Real Genius 永遠に歴史に名を残してほしい

**Comment by cookie-s** [comment]
GitHub Archiveくん、頼んだ

**Comment by cookie-s** [comment]
cb58a83af569e7180faae6f6651347304810c7d3
`oauth.access` を `oauth.v2.access` に置換しないといけない。
