### ISSUE TITLE
Firebaseに関連するプロジェクトの再編

### ISSUE THREAD

**Issue by hakatashi** [tsg-ut/slackbot#692]
現在、TSGのfirebaseプロジェクト (hakata-shi) を何らかの形で操作するコードは以下の場所で分散して管理されています。

- [achievement-viewer](https://github.com/tsg-ut/achievement-viewer)
  - Firebase Functions のコード, FirestoreのデータにアクセスするWebアプリ (実績ビューア)
- [slackbot](https://github.com/tsg-ut/slackbot)
  - Firestore のデータにアクセスするサーバーアプリ (slackbot)
- Firebaseの管理ページ
  - Firestore のセキュリティルールやプロジェクトの設定など

この構成には以下のような問題があります。

- 現状Functionsのコードはすべてachievementに関するものだが、そうでないFunctionsのコードを新しく書きたいときどこに置くべきか不明確になる
- 今後slackbot関連の請求を切り分けたくなったときに困る (#serverチャンネルも参照)
- hakatashiしかデプロイできない

よって、以下のようにFirebaseとGitHubのプロジェクトを再編しようと思っています。

- 「tsg-slackbot」という名前のFirebaseプロジェクト (=GCPプロジェクト) を新設し、TSGに関連する既存のデータなどを「hakata-shi」からそちらにすべて移す
- 「firebase-tsg-slackbot」という名前のリポジトリを新設し、Firebaseに関連するデータはすべてそこで管理するようにする
  - achievement-viewerとslackbotはこれに従属し、単にFirestoreにアクセスしたりFunctionsを呼び出したりするだけのコードのみ残す

構成とか、プロジェクトやリポジトリの名前について意見がある人は忌憚なくどうぞ〜

**Comment by hideo54** [comment]
Firebase のプロジェクトを新設・移行するのは大賛成です! あのあと案を詰めてくださりありがとうございます。

リポジトリ構成については、Firebase 専用のリポジトリを新しく作るよりは、既存の achievement-viewer や slackbot にコードを置くので十分かつ、そちらの方がわかりやすいように思うのですが、いかがですか?

(ちなみに、Functions の名前は "Firebase Functions" ではなく、Cloud Functions (for Firebase) だと思います。細かいところすいません…)

**Comment by hakatashi** [comment]
> リポジトリ構成については、Firebase 専用のリポジトリを新しく作るよりは、既存の achievement-viewer や slackbot にコードを置くので十分かつ、そちらの方がわかりやすいように思うのですが、いかがですか?

なるほど。その場合achievement-viewerにslackbotのコードを置くのは違和感があるので、slackbotリポジトリに置くことになると思うけど、ちょっとあのリポジトリはでかすぎて解体したい感がちょっとあったりする (まあ必要なコードではあるかもしれない)

**Comment by cookie-s** [comment]
:iiyo: あんま意見無い

**Comment by hakatashi** [comment]
とりあえずslackbotリポジトリにFirebase関連のコードを集約する方針でいじっていこうと思います

**Comment by hakatashi** [comment]
Slackbotの参照先を新projectに移しました

残タスク:

* achievement-viewerの参照先を新projectに移す

**Comment by hakatashi** [comment]
achievement-viewerの参照先も新projectになりました。
