### ISSUE TITLE
@tahoistの通知が動いていない

### ISSUE THREAD

**Issue by hakatashi** [tsg-ut/slackbot#737]
<img width="168" alt="image" src="https://user-images.githubusercontent.com/3126484/191124452-8f275278-de74-4c32-adc8-03503dcde768.png">

`@tahoist` の通知が動いてなさそう

_Originally posted by @hakatashi in https://github.com/tsg-ut/slackbot/issues/720#issuecomment-1251590903_

**Comment by cookie-s** [comment]
はかたし、いまのuser tokenがoauth v1のだとおもうので、できればrevokeしてから再認証してほしぶどう
ただそうすると、cleanerとかべつのtoken使用箇所も全部更新してもらうひつようがあると思うぶどう

まあ、それやりきるまで、hakatashi tokenのとこだけ、as_user消したcommitをrevertしてもよい

**Comment by cookie-s** [comment]
とりあえず通知は動いてるんでcloseします

**Comment by hakatashi** [comment]
ありがとにゃん

**Comment by cookie-s** [comment]
ぶどう
