### ISSUE TITLE
「今週の○○ランキング」で抜けが起きる

### ISSUE THREAD

**Issue by Szkieletor37** [tsg-ut/slackbot#791]
なんでなんだろ

例→ https://slack-log.tsg.ne.jp/C7AAX50QY/1673172002.604329

**Comment by settyan117** [comment]
botだからということではなく？

**Comment by settyan117** [comment]
https://github.com/tsg-ut/slackbot/blob/77c9c041c00fe97e4c391b52e56979590c05f64e/sushi-bot/index.ts#L464-L467

**Comment by Szkieletor37** [comment]
オワー
