### ISSUE TITLE
tunnel: 50番目のリアクションが無視される

### ISSUE THREAD

**Issue by pizzacat83** [tsg-ut/slackbot#88]
#85 は現状50個目のリアクションがblocksに入りきらないので無視している。かわいそう。

はみ出す場合に49個目と50個目で最終行を分け合うとかで対応できるかな。

**Comment by hakatashi** [comment]
これtextにもとのメッセージを配置してblockは全部reaction用に割くのでできないかな

**Comment by pizzacat83** [comment]
blocksを含むメッセージのtextは表示されないんですよね…

**Comment by hakatashi** [comment]
なるほど⋯⋯
