### ISSUE TITLE
最近コンテストの終了通知が来てない

### ISSUE THREAD

**Issue by hakatashi** [tsg-ut/slackbot#968]
なんか最近コンテストの終了通知が来てない？

[Slack Message](https://tsg-ut.slack.com/archives/C138GLKMW/p1733047463919649)

**Comment by sh-mug** [comment]
ATCODER_SESSION_ID を更新して次のコンテストまで様子見

**Comment by sh-mug** [comment]
来たのでクローズしてよさそう？
セッション ID は 180 日有効そう（次の期限は 2025-06-19）なので、またその時に手動更新するか、がんばって自動化するかのどちらかかなと思います
